#!/bin/bash

num_args=$#

#!echo $0
#!echo $num_args
INDENT="> "

# Default to synApps_6_1
VER="_6_1"
CHANGE_PREFIX="changePrefix"

case $num_args in
  3 )
    #!echo "$1"
    #!echo "$2"
    #!echo "$3"
    OS=$1
    VERSION=$2
    PREFIX=$3

    case $VERSION in 
      "5.8" )
        VER="_5_8"
        CHANGE_PREFIX="changePrefix.pl"
        ;;
      
      "6.0" )
        VER="_6_0"
        ;;
      
      "6.1" )
        VER="_6_1"
        ;;
      
      * )
        echo "Invalid synApps version.  Valid options: 5.8, 6.0, 6.1"
        exit 1
        ;;
    esac
    ;;

  2 )
    #!echo "$1"
    #!echo "$2"
    OS=$1
    PREFIX=$2
    # Default to synApps_6_1 for now
    VER="_6_1"
    ;;
  
  * )
    echo "Usage: makeIOC.sh <vxWorks|Linux|Darwin|Windows> <ioc_name>"
    echo "or"
    echo "Usage: makeiOC.sh <vxWorks|Linux|Darwin|Windows> <5.8|6.0|6.1> <ioc_name>"
    exit 1
    ;;
esac

# Validate OS choice
if [ "${OS}" != "Linux" ] && [ "${OS}" != "vxWorks" ] && [ "${OS}" != "Darwin" ] && [ "${OS}" != "Windows" ]
then
  echo "\"${OS}\" is not a valid OS choice. Choose vxWorks, Linux, Darwin or Windows."
  exit 1
else
  # Check for invalid Darwin versions
  if [ "${OS}" == "Darwin" ] && [ "${VER}" != "_5_8" ]
  then
    echo "Darwin is only available for synApps 5.8"
    exit 1
  fi
  BRANCH_OS="${OS}${VER}"
fi

# Check for existing IOC dir
if [ -d "${PREFIX}" ]
then
  echo "The \"${PREFIX}\" directory already exists."
  exit 1
fi 

# Clone the repo, switch to the desired branch rather than the master
echo "${INDENT}Cloning ${BRANCH_OS} of https://github.com/kmpeters/xxx.git..."
git clone https://github.com/kmpeters/xxx.git -b ${BRANCH_OS} ${PREFIX}

cd ${PREFIX}

echo "Switching to local deployed branch..."
git checkout -b deployed


echo "${INDENT}Changing IOC prefix..."
./${CHANGE_PREFIX} xxx ${PREFIX}

# Workaround for strange changePrefix.pl behavior on Windows
if [ "${OS}" == "Windows" ]
then
  echo "${INDENT}Deleting *.bak files"
  # Remove .bak files generated by changePrefix.pl (why do these files exist?)
  find . -name "*.bak" -type f -exec rm -f {} \;
fi

if [ "${VER}" == "_5_8" ]
then
  # Rename IOC startup directory
  mv iocBoot/ioc${OS} iocBoot/ioc${PREFIX}
fi

# Add renamed directories/files to git
git add iocBoot/ioc${PREFIX}
git add *${PREFIX}*

# Remove the changePrefix.pl script
echo "${INDENT}Removing ${CHANGE_PREFIX}..."
git rm ${CHANGE_PREFIX}

echo "${INDENT}Commiting changes to deployed branch..."
git commit -am "Initial commit of ${PREFIX} after running ${CHANGE_PREFIX}"

cd ..

echo "${INDENT} IOC ${PREFIX} (${OS}${VER}) created successfully"
